### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by isairey** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-isairey#1]
[WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-isairey/files/14670871/WEB.3.0.pdf)

**Comment by Luz1727** [comment]
20/20

**Comment by josealfredo79** [comment]
@isairey Falta agregar mas informacion de la Web 3.0 por favor... @Luz1727 Favor de evaluar mas objetivo..para la proxima no se registrara la informacion...
